document.addEventListener("DOMContentLoaded", () => {
  let words = ["able", "about", "account"];

  let wordArr;
  let displayList = document.getElementById("displayParent");
  displayBlanks = words => {
    let wordGenerator = words[Math.floor(Math.random() * words.length)];
    console.log(wordGenerator);

    wordArr = wordGenerator.split("");
    wordArr.forEach(el => {
      let childDisplay = document.createElement("li");
      childDisplay.className = "liItems";
      if (el) {
        childDisplay.innerText += " " + "_" + " ";
      }
      displayList.appendChild(childDisplay);
    });
  };

  displayBlanks(words);
  console.log(wordArr, "ar");

  document.addEventListener("keypress", event => {
    let keyCode = event.keyCode;
    let keyWord = String.fromCharCode(keyCode);

    wordArr.forEach(el => {
      if (el === keyWord) {
        body.replaceChild(ptag, ptag2);
      }
    });
    // return keyWord;
  });
});

//
// // let pTest = document.querySelector('#test')
// //console.log(pTest);
// document.addEventListener("DOMContentLoaded", Event => {
//   const randomGen = arr => {
//     let wordGenerator = arr[Math.floor(Math.random() * words.length)];
//     let test = document.querySelector("p");
//     test.innerText = wordGenerator.split("");
//     let ranWordSplit = wordGenerator.split("");
//     console.log(ranWordSplit, "the split word");
//     return ranWordSplit;
//   };
//   keyPresser();
//   let randWord = randomGen(words);
//   let hideWord = underScore(randWord);
// });
//
// const keyPresser = () => {
//   document.addEventListener("keypress", event => {
//     // const readlineSync = require('readline-sync');
//
//     //this allows the user to press a key which gives a code for the key
//     //the code is then converted back into a string and the
//     let keyCode = event.keyCode;
//     let keyWord = String.fromCharCode(keyCode);
//     console.log(keyWord);
//     window.alert("i work");
//
//     //global variables that will be used by the entire program
//     let guessedLetters = [];
//     let currentWordIndex;
//     let hiddenWord = [];
//     let gameStarted = false;
//     let hasFinished = false;
//     let wins = 0;
//     let maxTries = 0;
//
//     // this function generates a random word using an npm plug-in the automatically generates
//     //words from a library
//
//     const underScore = word => {
//       for (let i = 0; i < word.length; i++) {
//         hiddenWord[i] = "_";
//       }
//       return hiddenWord;
//     };
//
//     /*
//         assigning a variable with the random word generated by the function call
//         the variable hideWord will equal the call of the underscore function
//          */
//
//     //checks to see if the character entered is inside of the randomly generated word
//     const validity = (arg1, arg2) => {
//       while (maxTries < 5) {
//         console.log(arg2);
//         console.log(`you have ${maxTries} left`);
//         if (!arg1.includes(keyWord)) {
//           maxTries--;
//           console.log("attempt");
//           break;
//         } else {
//           for (let l = 0; l < arg1.length; l++) {
//             if (arg1[l] === keyWord && arg2[l] === "_") {
//               arg2[l] = keyWord;
//               //console.log(hiddenWord, "the hiddenWord")
//             }
//           }
//         }
//         console.log(attempt);
//       }
//     };
//
//     //function to check if the player won
//     const checkWin = () => {
//       if (hideWord.indexOf("_") === -1) {
//         document.getElementById("youwin-image").style.cssText =
//           "display: block";
//         document.getElementById("pressKeyTryAgain").style.cssText =
//           "display: block";
//         wins++;
//         hasFinished = true;
//       }
//     };
//
//     //function that will start the game to run
//     const runGame = () => {
//       validity(hideWord, randWord);
//     };
//
//     //this function runs the game
//     runGame();
//     // window.alert('i work')
//   });
// };
